### ISSUE TITLE
Functionality to let user choose frequency of alert emails (frontend)

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#12]
> This ticket is split into **frontend** and **backend**, so make sure that the `Label` of this issue is the one that applies to you.

**Context:**
Currently, a user is not given the choice as to how frequently they receive alerts--every time a new report is made, a new email is sent. This is perfectly fine for some people, however, others may see it as spam and want to unsubscribe which, of course, is not ideal. As such, we need to consider allowing users to choose the frequency when they fill out the 'Subscribe to the Mailing List' form.

**To-do:**
- [ ] Add another input field to the _Mailing List_ for the frequency. 
   - The 'id' of the input should be `emailFrequency` (backend is expecting this name)
   - Preferably the frequency should be represented as a dropdown or radio-button 
- [ ] Include no more than **4 options**, which you can name as you please, just communicate this in the comments of [this ticket](#11)

**Comment by raabyo** [comment]
Select id in email form has been renamed to "emailFrequency" and users are given these 4 options: 

- Once an hour (id="**oneHourFrequency**")
- Once every **3** hours (id="**threeHourFrequency**")
- Once every **8** hours (id="**eightHourFrequency**")
- Once a day (id="**dailyFrequency**")    

Let me know if you think we should change these frequencies
